POST http://localhost:8000/vendedor/produto/cadastrar HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODYxMzYyMDksImlzcyI6ImUtY29tbWVyY2Ugb2YgbWFuZ2EiLCJzdWIiOiI2NDdlNjZiNmU3ZmI0ZDIwZGViMjM1ZmEifQ.uE3rArTd2EJV4w6UKlsoTi1G0EPpbjo53UDgds7K2yRu2PSj6SutbcDVGbJkjWn0tx2jUjZ5hrzp_aaq6L1WTA

{
  "name": "arroz",
  "description": "arroz que delícia",
  "price": 2.99,
  "photo": "https://images.unsplash.com/photo-1516684732162-798a0062be99?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1587&q=80"

}